"""empty message

Revision ID: 0dce6f426074
Revises: d411651a905c
Create Date: 2022-06-04 17:54:18.291155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dce6f426074'
down_revision = 'd411651a905c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_contables', sa.Column('plantilla', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos_contables', 'plantilla')
    # ### end Alembic commands ###
