"""empty message

Revision ID: 1ae1c21e77fb
Revises: 5d787fbdc2c9
Create Date: 2021-12-27 20:13:25.788018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae1c21e77fb'
down_revision = '5d787fbdc2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_contables', sa.Column('tipodocumento', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos_contables', 'tipodocumento')
    # ### end Alembic commands ###
