"""empty message

Revision ID: 1b3a8b1607c3
Revises: 99dc76f7f680
Create Date: 2021-10-26 18:51:58.663455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3a8b1607c3'
down_revision = '99dc76f7f680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoDocumento', sa.String(length=5), nullable=True),
    sa.Column('numDocumento', sa.BigInteger(), nullable=True),
    sa.Column('pais', sa.String(length=20), nullable=True),
    sa.Column('departamento', sa.String(length=20), nullable=True),
    sa.Column('municipio', sa.String(length=20), nullable=True),
    sa.Column('primerNombre', sa.String(length=10), nullable=True),
    sa.Column('segundoNombre', sa.String(length=10), nullable=True),
    sa.Column('primerApellido', sa.String(length=10), nullable=True),
    sa.Column('segundoApellido', sa.String(length=10), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('codigoPostal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    # ### end Alembic commands ###
