"""empty message

Revision ID: 36e4ee86a87d
Revises: 52a2851be6fd
Create Date: 2022-08-16 11:01:28.108545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e4ee86a87d'
down_revision = '52a2851be6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asiento_ibfk_3', 'asiento', type_='foreignkey')
    op.create_foreign_key(None, 'asiento', 'cartera', ['id_cuenta'], ['id'])
    op.add_column('cartera', sa.Column('tipo', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_column('cartera', 'tipo')
    # ### end Alembic commands ###
