"""empty message

Revision ID: 52a2851be6fd
Revises: 786ed538ba2b
Create Date: 2022-08-03 19:25:31.651097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a2851be6fd'
down_revision = '786ed538ba2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asiento', 'proveedor', ['id_proveedor'], ['id'])
    op.create_foreign_key(None, 'asiento', 'cuenta', ['id_cuenta'], ['id'])
    op.add_column('registro', sa.Column('id_documentocontable', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registro', 'proveedor', ['id_proveedor'], ['id'])
    op.create_foreign_key(None, 'registro', 'documentos_contables', ['id_documentocontable'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registro', type_='foreignkey')
    op.drop_constraint(None, 'registro', type_='foreignkey')
    op.drop_column('registro', 'id_documentocontable')
    op.drop_constraint(None, 'asiento', type_='foreignkey')
    op.drop_constraint(None, 'asiento', type_='foreignkey')
    # ### end Alembic commands ###
