"""Create cuentas contables table

Revision ID: 5d787fbdc2c9
Revises: 1b3a8b1607c3
Create Date: 2021-12-11 21:37:46.477401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d787fbdc2c9'
down_revision = '1b3a8b1607c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('prefijo', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_contables')
    # ### end Alembic commands ###
