"""empty message

Revision ID: 786ed538ba2b
Revises: b02bd00b39c0
Create Date: 2022-06-23 20:52:55.649638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786ed538ba2b'
down_revision = 'b02bd00b39c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('id_cuenta', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('debitocredito', sa.Boolean(), nullable=True),
    sa.Column('valorbase', sa.Float(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('valortotal', sa.Float(), nullable=True),
    sa.Column('id_formapago', sa.Integer(), nullable=True),
    sa.Column('id_centrocosto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_registro'], ['registro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asiento')
    op.drop_table('registro')
    # ### end Alembic commands ###
