"""Create initial tables

Revision ID: 99dc76f7f680
Revises: 
Create Date: 2021-09-10 15:38:24.840856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dc76f7f680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=True),
    sa.Column('telephone', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('college_name', sa.String(length=80), nullable=True),
    sa.Column('college_direction', sa.String(length=120), nullable=True),
    sa.Column('college_nit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auxiliar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcuenta_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subcuenta_id'], ['subcuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subauxiliar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auxiliar_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['auxiliar_id'], ['auxiliar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subauxiliar')
    op.drop_table('auxiliar')
    op.drop_table('subcuenta')
    op.drop_table('cuenta')
    op.drop_table('grupo')
    op.drop_table('user')
    op.drop_table('clase')
    # ### end Alembic commands ###
