"""empty message

Revision ID: d411651a905c
Revises: a53adf50b872
Create Date: 2022-01-26 13:14:48.053985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd411651a905c'
down_revision = 'a53adf50b872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartera', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartera', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
