"""empty message

Revision ID: dd162fbd830c
Revises: b23010a689dc
Create Date: 2021-08-26 14:44:03.653898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd162fbd830c'
down_revision = 'b23010a689dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cartera', sa.Boolean(), nullable=True),
    sa.Column('tercero', sa.Boolean(), nullable=True),
    sa.Column('proveedor', sa.Boolean(), nullable=True),
    sa.Column('centroCosto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo')
    op.drop_table('clase')
    # ### end Alembic commands ###
